const APP_ROUTES = {
  LOGIN: '/login',
  SIGN_UP: '/sign-up',
  HOME: '/',
  CHAT: '/chat',
};

const SOCKET_EVENTS = {
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  JOIN_ROOM: 'joinRoom',
  LEAVE_ROOM: 'leaveRoom',
  MESSAGE: 'message',
  TYPING: 'typing',
  STOP_TYPING: 'stopTyping',
  USER_JOINED: 'userJoined',
  USER_LEFT: 'userLeft',
  ERROR: 'error',
};


const SOCKET_ERROR_CODES = {
  USER_EXISTS: 'USER_EXISTS',
  USER_DOES_NOT_EXIST: 'USER_DOES_NOT_EXIST',
  ROOM_DOES_NOT_EXIST: 'ROOM_DOES_NOT_EXIST',
  ROOM_EXISTS: 'ROOM_EXISTS',
  USER_NOT_IN_ROOM: 'USER_NOT_IN_ROOM',
  USER_ALREADY_IN_ROOM: 'USER_ALREADY_IN_ROOM',
  INVALID_ROOM: 'INVALID_ROOM',
  INVALID_USER: 'INVALID_USER',
  INVALID_MESSAGE: 'INVALID_MESSAGE',
  INVALID_TYPING: 'INVALID_TYPING',
  INVALID_STOP_TYPING: 'INVALID_STOP_TYPING',
  INVALID_USER_JOINED: 'INVALID_USER_JOINED',
  INVALID_USER_LEFT: 'INVALID_USER_LEFT',
  INVALID_ERROR: 'INVALID_ERROR',
};

export {
  APP_ROUTES,
  SOCKET_EVENTS,
  SOCKET_ERROR_CODES,
}